services:
  app:
    image: chat-delete-links-bot:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - monitoring
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
  prometheus:
    image: prom/prometheus:v3.7.3
    restart: "no"
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  grafana:
    image: grafana/grafana:12.3.0
    restart: "no"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: true
      GF_INSTALL_PLUGINS: prometheus
    networks:
      - monitoring
    healthcheck:
      test: curl --fail -s http://localhost:3000/api/health || exit 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  prometheus_data:
  grafana_data:
networks:
  monitoring:
    driver: bridge