server:
  port: 8081
spring:
  application:
    name: chat-manager-bot
telegram:
  secret-word-to-pass: ${SECRET_WORD_TO_PASS}
  urls:
    white-list: ${URLS_WHITE_LIST}
  chats:
    white-list: ${CHAT_IDS_WHITE_LIST}
  bot:
    token: ${BOT_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true