server:
  port: 8081

spring:
  application:
    name: chat-delete-links-bot

telegram:
  secret-word-to-pass: ${SECRET_WORD_TO_PASS}
  urls:
    white-list: ${URLS_WHITE_LIST}
  chats:
    white-list: ${CHAT_IDS_WHITE_LIST}
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}